# Generated by Django 5.0.1 on 2024-02-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_confirmation_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
