# Generated by Django 5.0.1 on 2024-02-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
