# Generated by Django 5.0.1 on 2024-02-07 23:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='preferences',
            name='key',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(code='invalid_key', message='Key should not contain spaces or downcase.', regex='^[A-Z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='preferences.client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('user', 'USER')], default='user', max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='preferences',
            unique_together={('client', 'key')},
        ),
    ]
